# Generated by Django 3.2.12 on 2022-02-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camera',
            new_name='Image',
        ),
    ]
